### PR TITLE
[WIP] preliminary windows support

### PR DESCRIPTION
**Pull request by axos88**
This PR contains quite a lot of changes, so please, handle with care.
It is a work in progress, but I would like you input and opinion on my solutions, and what it needs to make it mergable to master.

The pull request adds preliminary, partial support for windows. 

Larger changes:
  - all bash resources have been exchanged with execute resources, as it is cross-platform and they were executing a single command anyways.
  - grepping has been exchanged with building the filtering command with a helper function, that outputs a grep on linux and findstr on windows
  - support for most of the declared glassfish resources have been adapted to use the filter builder
  - timeouts have been adjusted to node['glassfish']['asadmin']['timeout'] + 5
  - the more complex resources, such as domain and deployable have been given a second provider for windows.

TODO:
  - support for mq resources
  - not tied to windows support, but refactor the cookbook and remove a LOT of code repetition with base classes / base modules. Will be a separate PR after this one is merged.

### CODE REVIEW

**Comment by axos88** [comment]
#96

**Comment by realityforge** [comment]
Hi,

Just dropping a comment to say I am looking at this ... it is just taking a while to get enough time to test it all out ;)

**Comment by axos88** [comment]
Hi,

Thanks for letting me know.
Once this is update, I have a major refactor in my head to eliminate a lot of code repetition, once I get enough time to do it.

**Comment by realityforge** [comment]
Hi, As this is a large change I have decided to merge across single changes at a time and test them out across our infrastructure. So far I recreated the changes you made to make timeouts configurable, replaced the bash resources with execute resources and made the configuration of user/group for commands skipped on the windows platform. These changes are in master. Could you check them over to make sure I have got it right and then update the pull request against master.

Thanks for the submission!

**Comment by axos88** [comment]
Sure thing. Thanks for your input, I will update the PR as my time allow

**Comment by axos88** [comment]
@realityforge  updated.

**Comment by axos88** [comment]
@realityforge ping

**Comment by axos88** [comment]
@realityforge ping

**Comment by axos88** [comment]
Hey @TeroPihlaja

It's been a while, hasn't it :))

I've switched workplace in the meantime and are no longer working on windows (thank god!), so I won't be able to assist you any further.
But I do remember having issues restarting glassfish with NSSM, and AFAIK the guys wound up switching back to glassfish's own service instead after I left.

**Comment by TeroPihlaja** [comment]
I have continued work on this on https://github.com/realityforge/chef-glassfish/pull/112

**Pull request closed without merging**
