### PR TITLE
Support for systemd and fixed issue with SysV using environment variables

### PR DESCRIPTION
**Pull request by jimmycliff**

### CODE REVIEW

**Comment by realityforge** [comment]
Eyeballing it looks fine. Will try and get it tested and merged in soon. Sorry for taking a while to respond ... have a small baby and my time is getting soaked up there ;)

**Comment by jimmycliff** [comment]
Cool..  Thanks @realityforge.  Hear you on the baby thing - got a 1 and 3 at home, as well.   Enjoy it!

**Comment by jimmycliff** [comment]
Noticed an issue with the systemd syntax, which should be fixed now.   ``Environment`` should look like this:
```
Environment="LC_ALL=en_US.UTF-8"
Environment="LD_LIBRARY_PATH=/path/to/lib"
Environment="LD_PRELOAD=/path/to/lib/libjsig.so"
```
Not this:
```
Environment="LC_ALL=en_US.UTF-8 LD_LIBRARY_PATH=/path/to/lib LD_PRELOAD=/path/to/lib/libjsig.so"
```

**Comment by realityforge** [comment]
Thanks - finally got to merging it.

**Pull request merged**
