### PR TITLE
Add prefix option so that GF will be installed in specified location

### PR DESCRIPTION
**Pull request by jimmycliff**
This will install glassfish in the location specified by node['glassfish']['install_dir'].

### CODE REVIEW

**Comment by jimmycliff** [comment]
It didn't seem to be enough by just setting 'base_dir'(at least in my testing)..     I was setting both 'base_dir' and 'install_dir' and it was not installing GF in a specific location.  Perhaps we should be using base_dir for prefix in the archive resource call?

**Comment by mathomas** [comment]
We actually use the attribute_driven_domain recipe, rather than using the resources directly.  The 'base_dir' attribute has been working for us in that mode for a long time (but again, our fork of this cookbook is way out of date).  So take my comment with a grain of salt -- I would just be surprised if functionality has been lost as the cookbook has been maintained.

**Comment by jimmycliff** [comment]
Yea we are also using the attribute_driven_domain recipe.   I am setting attributes and then including said recipe in my cookbook.   The attribute_driven_domain recipe then includes the default recipe which calls the archive resource. 

Are you setting the base_dir at default level?   eg node.default['glassfish']['base_dir'] = $BASEDIR
or are you using any override/force_override to set it?

What version of the glassfish cookbook are you using?

**Comment by jimmycliff** [comment]
If you look at this commit (specifically recipes/default.rb):

https://github.com/realityforge/chef-glassfish/commit/cfb4a389494c84f31387d53d3786f0e2f52547a6

It appears it was switched to use archive from a combination of remote_file and bash scripts.   This could be when it broke?

**Comment by realityforge** [comment]
Thanks for the contribution!

**Comment by mathomas** [comment]
@jimmycliff 
Sounds like you were right all along. The fact that Peter merged your change says something!  :-)

Sorry I wasn't more responsive to your last question.  We're on a very old fork (like over a year old) of the cookbook that I had customized in a non-shareable way, and that's been working for our needs.  I'm pretty out of the loop on the newer versions.

Someday we need to upgrade.  Someday...

**Pull request merged**
